[project]
name = "error-log-alert-microservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kevin Wang", email = "aoling.wang@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
error-log-alert-microservice = "error_log_alert_microservice:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
