[project]
name = "error-log-alert-microservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kevin Wang", email = "aoling.wang@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "httpx>=0.28.1",
    "python-dotenv>=1.2.3",
]

[project.scripts]
error-log-alert-microservice = "error_log_alert_microservice.main:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "ruff>=0.16.5",
    "ty>=0.0.78",
]
